(module
  (type $TypeInfoBase (sub (struct (field $$tag i32) (field $$parent (ref null $TypeInfoBase)))))
  (type $Object (sub (struct (field $$typeinfo (mut (ref $TypeInfoBase))))))
  (type $TypeInfoBase1 (sub (struct (field $$tag i32) (field $$parent (ref null $TypeInfoBase1)))))
  (type $Object1 (sub (struct (field $$typeinfo (mut (ref $TypeInfoBase1))))))
  (type $Unit_typeinfo (sub $TypeInfoBase1 (struct (field $$tag i32) (field $$parent (ref null $TypeInfoBase1)))))
  (type $Unit (sub $Object1 (struct (field $$typeinfo (mut (ref $TypeInfoBase1))))))
  (type $Unit_init (func (param $this (ref null any)) (result (ref null any))))
  (type $Unit_ctor (func (result (ref null any))))
  (type $div_impl (func (param $lhs (ref null any)) (param $rhs (ref null any)) (result (ref null any))))
  (type $eq_impl (func (param $lhs (ref null any)) (param $rhs (ref null any)) (result (ref null any))))
  (type $ge_impl (func (param $lhs (ref null any)) (param $rhs (ref null any)) (result (ref null any))))
  (type $gt_impl (func (param $lhs (ref null any)) (param $rhs (ref null any)) (result (ref null any))))
  (type $le_impl (func (param $lhs (ref null any)) (param $rhs (ref null any)) (result (ref null any))))
  (type $lt_impl (func (param $lhs (ref null any)) (param $rhs (ref null any)) (result (ref null any))))
  (type $minus_impl (func (param $lhs (ref null any)) (param $rhs (ref null any)) (result (ref null any))))
  (type $mod_impl (func (param $lhs (ref null any)) (param $rhs (ref null any)) (result (ref null any))))
  (type $neg_impl (func (param $arg (ref null any)) (result (ref null any))))
  (type $neq_impl (func (param $lhs (ref null any)) (param $rhs (ref null any)) (result (ref null any))))
  (type $not_impl (func (param $arg (ref null any)) (result (ref null any))))
  (type $plus_impl (func (param $lhs (ref null any)) (param $rhs (ref null any)) (result (ref null any))))
  (type $pos_impl (func (param $arg (ref null any)) (result (ref null any))))
  (type $times_impl (func (param $lhs (ref null any)) (param $rhs (ref null any)) (result (ref null any))))
  (type $mlx_exn (func (param $ex (ref null any))))
  (type $entry (func (result (ref null any))))
  (type $start (func))
  (type $virtual1 (func (param $this (ref null any)) (result (ref null any))))
  (type $Box_typeinfo (sub $TypeInfoBase (struct (field $$tag i32) (field $$parent (ref null $TypeInfoBase)) (field $slot0 (mut (ref null $virtual1))))))
  (type $Box (sub $Object (struct (field $$typeinfo (mut (ref $TypeInfoBase))) (field $value (mut (ref null any))))))
  (type $Box_init (func (param $this (ref null any)) (param $value (ref null any)) (result (ref null any))))
  (type $Box_ctor (func (param $value (ref null any)) (result (ref null any))))
  (type $entry1 (func (result (ref null any))))
  (import "system" "Unit_init" (func $Unit_init (type $Unit_init)))
  (import "system" "Unit_Unit" (func $Unit_Unit (type $Unit_ctor)))
  (import "system" "div_impl" (func $div_impl (type $div_impl)))
  (import "system" "eq_impl" (func $eq_impl (type $eq_impl)))
  (import "system" "ge_impl" (func $ge_impl (type $ge_impl)))
  (import "system" "gt_impl" (func $gt_impl (type $gt_impl)))
  (import "system" "le_impl" (func $le_impl (type $le_impl)))
  (import "system" "lt_impl" (func $lt_impl (type $lt_impl)))
  (import "system" "minus_impl" (func $minus_impl (type $minus_impl)))
  (import "system" "mod_impl" (func $mod_impl (type $mod_impl)))
  (import "system" "neg_impl" (func $neg_impl (type $neg_impl)))
  (import "system" "neq_impl" (func $neq_impl (type $neq_impl)))
  (import "system" "not_impl" (func $not_impl (type $not_impl)))
  (import "system" "plus_impl" (func $plus_impl (type $plus_impl)))
  (import "system" "pos_impl" (func $pos_impl (type $pos_impl)))
  (import "system" "times_impl" (func $times_impl (type $times_impl)))
  (import "system" "start" (func $start (type $start)))
  (import "system" "entry" (func $entry (type $entry)))
  (import "system" "Unit_typeinfo" (global $Unit_typeinfo (ref $Unit_typeinfo)))
  (import "system" "Unit$inst" (global $Unit$inst (mut (ref null $Unit))))
  (global $Box_typeinfo (export "Box_typeinfo") (ref $Box_typeinfo) (struct.new $Box_typeinfo
    (i32.const 1)
    (ref.null $TypeInfoBase)
    (ref.func $Box_answer)))
  (func $Box_init (export "Box_init") (type $Box_init) (param $this (ref null any)) (param $value (ref null any)) (result (ref null any))
    (block (result (ref null any))
      (struct.set $Box $value
        (ref.cast (ref $Box)
          (local.get $this))
        (local.get $value))
      (return
        (local.get $this))))
  (func $Box_ctor (export "Box_ctor") (type $Box_ctor) (param $value (ref null any)) (result (ref null any))
    (local $this (ref null any))
    (block (result (ref null any))
      (local.set $this
        (struct.new $Box
          (global.get $Box_typeinfo)
          (ref.null any)))
      (drop
        (call $Box_init
          (local.get $this)
          (local.get $value)))
      (return
        (local.get $this))))
  (func $Box_answer (export "Box_answer") (type $virtual1) (param $this (ref null any)) (result (ref null any))
    (block
      (return
        (struct.get $Box $value
          (ref.cast (ref $Box)
            (local.get $this))))
      (unreachable)))
  (func $entry1 (export "entry") (type $entry1) (result (ref null any))
    (global.get $Unit$inst))
  (elem $Box_init declare func $Box_init)
  (elem $Box_ctor declare func $Box_ctor)
  (elem $Box_answer declare func $Box_answer)
  (elem $entry declare func $entry1))